// <auto-generated />
namespace HouseholdManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class transactiontodoitemremovefk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactiontodoitemremovefk));
        
        string IMigrationMetadata.Id
        {
            get { return "202407170425221_transaction-todoitem-remove-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
